logging:
  level:
    root: info
    com.bootdo: info
    com.cb: debug
bootx:
  weixin:
    applet:
      appid: hello
      secret: 2
  security:
      shiro:
        enable: false
spring:
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.01:3306/bootx?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
  data:
    # mongodb连接
    mongodb:
      uri: mongodb://file:123456@sql.7326it.club:27017/file

